### ISSUE TITLE
Return to previous design

### ISSUE THREAD

**Issue by tansiret** [os-js/osjs-standard-theme#20]
No offense, but this one looks a bit better imo:
![image](https://user-images.githubusercontent.com/40173707/112953624-508ba780-9146-11eb-98b8-60b8736e7120.png)

**Comment by andersevenrud** [comment]
But it's the same design though ?! What's really changed is the application layouts.

**Comment by tansiret** [comment]
> But it's the same design though ?! What's really changed is the application layouts.

The menu button looks much better in the past one. Also apps look definitely better.

**Comment by andersevenrud** [comment]
The menu is customizable.

I don't have any time to change all the apps with my current work situation, so I'm closing this. If you wanna take a look at this yourself then please do and I'll re-open (or if anyone else wants to try it).
